[package]
name = "lc-rust"
version = "0.1.0"
authors = ["Ashley Cutmore <acutmore@users.noreply.github.com>"]

[lib]
name = "lc"
path = "src/lib.rs"
crate-type = ["lib", "cdylib"]

[dependencies]
lazy_static = "1.0.0"
regex = "0.2"
